name: 'Wait for Vercel Preview'
description: 'Wait for Vercel Deploy Preview to complete. Requires to be run on pull_request or push.'
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  token:
    description: 'The Vercel token'
    required: true
  team_id:
    description: 'The Vercel team ID'
    required: true
  app:
    description: 'The app name to find the deployment for.'
    required: true
  commit_sha:
    description: 'The commit we should find the deployment for'
    required: true
  commit_branch:
    description: 'The branch we should find the deployment for'
    required: true
  max_timeout:
    description: 'The amount of time (in seconds) to spend waiting on Vercel. Defaults to 120 seconds'
    default: '120'
    required: false
  initial_timeout:
    description: 'The amount of time (in seconds) to wait before the first check. Defaults to 5 seconds'
    default: '5'
    required: false
  check_interval:
    description: 'How often (in seconds) should we make the HTTP request checking to see if the deployment is available? Defaults to 2 seconds'
    default: '2'
    required: false

outputs:
  url:
    description: 'The fully qualified deploy preview URL'
runs:
  using: 'node20'
  main: 'dist/index.js'
